"""
MalSpectra - Ghidra Script Generator
Generates analysis scripts for Ghidra headless execution

Developer: Sai Srujan Murthy
Email: saisrujanmurthy@gmail.com
"""

from pathlib import Path
from typing import Optional


class GhidraScriptGenerator:
    """
    Generates Ghidra analysis scripts in Python format.
    Scripts are compatible with Ghidra's headless analyzer.
    """
    
    def __init__(self, output_dir: Optional[Path] = None):
        """
        Initialize script generator.
        
        Args:
            output_dir: Directory to save generated scripts
        """
        if output_dir is None:
            output_dir = Path(__file__).parent / "scripts"
        
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_function_analysis_script(self, output_json: str) -> Path:
        """
        Generate a Python script for Ghidra that analyzes functions.
        
        Args:
            output_json: Path where JSON output should be saved
        
        Returns:
            Path to the generated script
        """
        script_content = f'''# Ghidra Function Analysis Script
# Generated by MalSpectra
# Analyzes functions and exports to JSON

from ghidra.program.model.listing import Function
from ghidra.app.decompiler import DecompInterface
import json

def analyze_functions():
    """Extract function information from current program."""
    
    # Get current program
    program = getCurrentProgram()
    listing = program.getListing()
    function_manager = program.getFunctionManager()
    
    # Setup decompiler
    decompiler = DecompInterface()
    decompiler.openProgram(program)
    
    functions_data = []
    
    # Iterate through all functions
    for function in function_manager.getFunctions(True):
        func_info = {{}}
        
        # Basic function info
        func_info['name'] = function.getName()
        func_info['entry_point'] = str(function.getEntryPoint())
        func_info['address'] = str(function.getEntryPoint())
        func_info['size'] = function.getBody().getNumAddresses()
        
        # Get function signature
        func_info['signature'] = str(function.getSignature())
        
        # Get parameter count
        func_info['parameter_count'] = function.getParameterCount()
        
        # Get return type
        func_info['return_type'] = str(function.getReturnType())
        
        # Check if external/imported
        func_info['is_external'] = function.isExternal()
        func_info['is_thunk'] = function.isThunk()
        
        # Get calling functions (references TO this function)
        callers = []
        for ref in function.getSymbol().getReferences():
            caller_addr = ref.getFromAddress()
            caller_func = listing.getFunctionContaining(caller_addr)
            if caller_func:
                callers.append(str(caller_func.getName()))
        func_info['called_by'] = list(set(callers))
        
        # Get called functions (references FROM this function)
        called = []
        body = function.getBody()
        for addr in body.getAddresses(True):
            refs = listing.getCodeUnitAt(addr).getReferencesFrom()
            for ref in refs:
                to_addr = ref.getToAddress()
                called_func = listing.getFunctionContaining(to_addr)
                if called_func:
                    called.append(str(called_func.getName()))
        func_info['calls'] = list(set(called))
        
        functions_data.append(func_info)
    
    # Export to JSON
    output_file = r'{output_json}'
    with open(output_file, 'w') as f:
        json.dump({{
            'program_name': program.getName(),
            'function_count': len(functions_data),
            'functions': functions_data
        }}, f, indent=2)
    
    print("[MalSpectra] Analysis complete. Functions exported to: " + output_file)
    print("[MalSpectra] Total functions analyzed: " + str(len(functions_data)))

# Run analysis
analyze_functions()
'''
        
        # Save script
        script_path = self.output_dir / "analyze_functions.py"
        with open(script_path, 'w') as f:
            f.write(script_content)
        
        return script_path
    
    def generate_strings_extraction_script(self, output_json: str) -> Path:
        """
        Generate a script to extract strings from binary.
        
        Args:
            output_json: Path where JSON output should be saved
        
        Returns:
            Path to the generated script
        """
        script_content = f'''# Ghidra Strings Extraction Script
# Generated by MalSpectra

import json

def extract_strings():
    """Extract defined strings from current program."""
    
    program = getCurrentProgram()
    listing = program.getListing()
    
    strings_data = []
    
    # Iterate through all defined strings
    for data in listing.getDefinedData(True):
        if data.hasStringValue():
            string_info = {{
                'address': str(data.getAddress()),
                'value': str(data.getValue()),
                'length': len(str(data.getValue())),
                'type': str(data.getDataType())
            }}
            strings_data.append(string_info)
    
    # Export to JSON
    output_file = r'{output_json}'
    with open(output_file, 'w') as f:
        json.dump({{
            'program_name': program.getName(),
            'string_count': len(strings_data),
            'strings': strings_data
        }}, f, indent=2)
    
    print("[MalSpectra] Strings extracted: " + str(len(strings_data)))

# Run extraction
extract_strings()
'''
        
        script_path = self.output_dir / "extract_strings.py"
        with open(script_path, 'w') as f:
            f.write(script_content)
        
        return script_path
    
    def get_script_dir(self) -> Path:
        """
        Get the scripts directory.
        
        Returns:
            Path to scripts directory
        """
        return self.output_dir


if __name__ == "__main__":
    # Test script generation
    generator = GhidraScriptGenerator()
    script = generator.generate_function_analysis_script("/tmp/test_output.json")
    print(f"Generated script: {script}")
